### ISSUE TITLE
use antd Custom Confirm Modal 

### ISSUE THREAD

**Issue by zhulinpinyu** [zhulinpinyu/zhulinpinyu.github.io#15]
```css
.confirm-modal-footer{
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  button {
    font-weight: bolder;
    font-size: 23px;
  }
}
```

```javascript
import React from 'react'
import { Modal, Button} from 'antd'

export default class ConfirmModal extends React.PureComponent {

  render() {
    const {visible, title, content, onCancel, onOk} = this.props
    return (
      <Modal
        visible={visible}
        title={title}
        mask={false}
        closable={false}
        centered
        maskClosable
        destroyOnClose={true}
        footer={<div className="confirm-modal-footer">
          <Button key="back" size="large" type="danger" onClick={onCancel}>
            没有
          </Button>
          <Button key="submit" size="large" type="primary" onClick={onOk}>
            有
          </Button>
        </div>}
      >
        {content}
      </Modal>
    )
  }
}
```

使用：

```javascript
<ConfirmModal
            visible={currentItem.category === "Handbag"}
            title={null}
            content=""
            onOk={() => {}}
            onCancel={() => {}}
          />
```

效果：

<img width="444" alt="Screen Shot 2019-09-04 at 15 03 17" src="https://user-images.githubusercontent.com/1920496/64232767-2e5b8480-cf25-11e9-9abc-b0b2f3f7085a.png">
